### ISSUE TITLE
ripoff, why did you copy their readme

### ISSUE THREAD

**Issue by TrashUwU** [issac756/poketwo-Autocatcher#3]
Sure , what's your readme I bet I saw many people with exact readme so you copied tbh I saw exact one with CHambur repo so what are you?
>Now don't go on a say you are one of a kind that would make me laugh.
As far I rember nexus readme wasn't anything like mine 

Well, there's nothing called Chamburr PokeAssistant RN 😂. Btw did you visit the Rohtak mental hospital?
> So that changes the facts for you , clearly shows your age here . I won't waste time talking to kids
P.S I don't need to cuz you are the one being stupid here , may be you should go for your daily check up dw I won't ever say to anyone that some parts of your brain 🧠 is missing

**Comment by TrashUwU** [comment]
The issue was closed by someone who copied Hyperclaw's auto catcher.
 > Yes cuz you failed you use the free version he had in GitHub , cuz of your low lvl IQ you except all to do that what a Shame may be do a background search before speaking facts
Also imagine having balls to copy someone's code and promoting like it's handmade can't be me.

**Comment by issac756** [comment]
On side note do you think , nexus gonna hand you the models he's been working cuz your are bitching around him , sorry man you are getting Nothin from him and if I were you I would save my energy hanging around him .
And yea did I make you cry 😢

**Comment by issac756** [comment]
People do love to speak alot especially who is no one like you  lol 😂 get good  . If it was hyper claw exact copy he should have alr contacted me regarding it , which he didn't or do you think he doesn't know about it on side note he does know about it and just console log and you decided it's hypers get good , search more before speaking facts .

**Comment by TrashUwU** [comment]
> People do love to speak alot especially who is no one like you lol  get good . If it was hyper claw exact copy he should have alr contacted me regarding it , which he didn't or do you think he doesn't know about it on side note he does know about it and just console log and you decided it's hypers get good , search more before speaking facts .

You deleted his comments.
>Hypers comments I don't need to , I'm not nexus to do so.
P.S it was personal info which wasn't supposed to be seen by all and what matters is issue wasn't closed by me.

**Comment by TrashUwU** [comment]
You got IP grabbed by a random 13 year old. Now is it Hyper this time? How did he get your info?

>On slr and I alr talked about that lol , if he thinks he got my ip lol , I will just let him enjoy his day and again' how's that releated to this you are sounding like way stupid here . 
-
P.s hyper isn't a kid to do such stupid things and when I meant personal it's not even about ip lmfao

**Comment by TrashUwU** [comment]
> On side note do you think , nexus gonna hand you the models he's been working cuz your are bitching around him , sorry man you are getting Nothin from him and if I were you I would save my energy hanging around him .
> And yea did I make you cry 😢

I use convnet. What'll I do with his Keras Model? It will not fit into Replit's Storage.
